### ISSUE TITLE
Error installing coloration: coloration requires Ruby version ~> 1.9.

### ISSUE THREAD

**Issue by herrbischoff** [sickill/coloration#17]
### Environment

Mac OS X 10.10.3

```
$ uname -a
Darwin Sam.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
```

### Problem

I have a current ruby version installed:

```
$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
```

But `coloration` refuses to install:

```
$ gem install coloration
ERROR:  Error installing coloration:
	coloration requires Ruby version ~> 1.9.
```

I have checked other gems requiring ruby > 1.9 — they work. Any ideas?

**Comment by herrbischoff** [comment]
I have been able to install it from the GitHub source with the following steps:

```
gem install specific_install
gem specific_install -l https://github.com/sickill/coloration
```

Apparently the current gem file is somehow faulty. This should probably be rectified.

**Comment by gavinlaking** [comment]
Glad you got up and running. We'll try to get another version of the gem pushed to RubyGems as soon as possible.

**Comment by sickill** [comment]
@gavinlaking I have just added you as a gem owner on rubygems.org, feel free to release whenever it makes sense :)

**Comment by gavinlaking** [comment]
Thanks, I've just released v0.4.0. :-)

**Comment by ku1ik** [comment]
Cool. Btw, looks like you've forgotten to update the date in .gemspec ;) https://rubygems.org/gems/coloration

**Comment by ku1ik** [comment]
I wonder if `s.date = Date.today` in a gemspec file is a good idea...

**Comment by herrbischoff** [comment]
Thanks! I'm happy to report that this gem installs correctly.

**Comment by gavinlaking** [comment]
Ah, I saw the 'Date.today' entry in the gemspec, thought it was strange but left it alone. I don't think it is a required field, might be worth removing it.

**Comment by ku1ik** [comment]
@gavinlaking You did? I was wondering if _adding_ it would be a great idea. I don't see it anywhere in this project's gemspec at the moment.

**Comment by gavinlaking** [comment]
:pineapple: I must have been imagining seeing that in the gemspec. Where was I?!

Anyway, I'm not sure this is a good idea; this would probably confuse gem servers and other authors. 'date' is no longer mentioned as part of the gemspec specification, so I vote dropping it altogether.

http://guides.rubygems.org/specification-reference/

**Comment by ku1ik** [comment]
+1 for dropping.
11 cze 2015 19:37 "Gavin Laking" notifications@github.com napisał(a):
